# Generated by Django 4.2 on 2023-05-31 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cronometro',
        ),
    ]
